import fs from "fs";
import path from "path";

const projectRoot = process.cwd();
const galleryDir = path.join(projectRoot, "client", "public", "gallery");
const outFile = path.join(projectRoot, "client", "src", "data", "galleryImages.ts");

function isImage(name) {
  return /\.(png|jpe?g|webp)$/i.test(name);
}

function naturalSort(a, b) {
  return a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" });
}

if (!fs.existsSync(galleryDir)) {
  console.error("Gallery directory not found:", galleryDir);
  process.exit(1);
}

const files = fs.readdirSync(galleryDir).filter(isImage).sort(naturalSort);

const urls = files.map((f) => `/gallery/${f}`);

const header =
  `// AUTO-GENERATED FILE. DO NOT EDIT.\n` +
  `// Generated by scripts/generate_gallery_list.mjs\n\n` +
  `export const GALLERY_IMAGES: string[] = [\n`;

const body = urls.map((u) => `  ${JSON.stringify(u)},`).join("\n");

const footer = `\n];\n`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, header + body + footer, "utf8");

console.log(`Generated: ${path.relative(projectRoot, outFile)} (Images: ${urls.length})`);
