import fs from 'node:fs';
import path from 'node:path';
import { articles } from '../client/src/data/articles';

const ROOT = process.cwd();
const PUBLIC_DIR = path.join(ROOT, 'client', 'public', 'article-data');
const INDEX_PATH = path.join(ROOT, 'client', 'src', 'data', 'articlesIndex.ts');

// Ensure public directory exists
fs.mkdirSync(PUBLIC_DIR, { recursive: true });

console.log(`[split-articles] Starting to split ${articles.length} articles...`);

// 1. Write individual JSON files for each article containing the full data
let jsonCount = 0;
for (const a of articles) {
  if (!a.slug) {
    console.warn(`[split-articles] Warning: Article ID ${a.id} is missing a slug!`);
    continue;
  }
  const fileTarget = path.join(PUBLIC_DIR, `${a.slug}.json`);
  fs.writeFileSync(fileTarget, JSON.stringify(a, null, 2), 'utf8');
  jsonCount++;
}

console.log(`[split-articles] Successfully generated ${jsonCount} individual JSON files in ${PUBLIC_DIR}`);

// 2. Generate a lightweight index containing metadata only (excluding content and faqs)
const indexItems = articles.map((a) => {
  // Destructure to separate full content & faqs
  const { content, contentEn, faqAr, faqEn, ...meta } = a;
  return meta;
});

const indexContent = `// Automatically generated by scripts/split_articles.ts during build.
// DO NOT EDIT THIS FILE DIRECTLY. Edit client/src/data/articles.ts instead.

export interface ArticleImage {
  url: string;
  alt: string;
  creditName: string;
  creditUrl: string;
  license: string;
}

export interface ArticleIndexItem {
  id: number;
  title: string;
  titleEn: string;
  category: string;
  categoryEn: string;
  categoriesAr?: string[];
  categoriesEn?: string[];
  date: string;
  readTime: string;
  readTimeEn?: string;
  author: string;
  slug: string;
  image?: ArticleImage;
  excerpt?: string;
  excerptEn?: string;
}

export const articlesIndex: ArticleIndexItem[] = ${JSON.stringify(indexItems, null, 2)};
`;

fs.writeFileSync(INDEX_PATH, indexContent, 'utf8');
console.log(`[split-articles] Successfully generated lightweight index of ${indexItems.length} items at ${INDEX_PATH}`);
console.log('[split-articles] Complete.');
